apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: {{ template "kafka-comp.fullname" . }}-bridge
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  bootstrapServers: {{ .Values.global.kafkaBootstrapServers | quote }}
  http:
    port: 8080
