apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ template "kafka-comp.fullname" . }}-connect
  namespace: {{ .Release.Namespace }}
  {{- if .Values.connect.annotations }}
  annotations: {{- toYaml .Values.connect.annotations | nindent 4 }}
  {{- end }}
spec:
  image: {{ .Values.connect.image | quote }}
  version: {{ .Values.connect.version }}
  replicas: {{ .Values.connect.replicas }}
  bootstrapServers: {{ .Values.global.kafkaBootstrapServers | quote }}
  {{- if .Values.connect.tls }}
  tls: {{- toYaml .Values.connect.tls | nindent 4 }}
  {{- end }}
  config: {{- toYaml .Values.connect.config | nindent 4 }}
