apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ if .Values.consumer.enabled }}{{ .Values.consumer.replicas }}{{ else }}0{{ end }}
  selector:
    matchLabels:
      app: {{ .Values.consumer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.consumer.name }}
    spec:
      containers:
      - name: perf-test
        image: confluentinc/cp-kafka:latest
        command:
        - /bin/sh
        - -c
        - |
          kafka-consumer-perf-test \
            --topic {{ .Values.topic }}  \
            --show-detailed-stats \
            --group {{ .Values.consumer.group }} \
            --broker-list {{ .Values.bootstrapServer }} \
            --reporting-interval {{ .Values.consumer.reportingInterval }} \
            --messages {{ .Values.consumer.messages }}
