apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.topic }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
