global:
  ui:
    configName: &kafkaUIConfigMap kafka-ui-configmap

kafka:
  controller:
    replicaCount: 3
    persistence:
      enabled: false
    # resources:
    #   requests:
    #     cpu: 200m
    #     memory: 500m
    #   limits:
    #     cpu: 200m
    #     memory: 500m

  broker:
    replicaCount: 4
    persistence:
      enabled: false
    # resources:
    #   requests:
    #     cpu: 200m
    #     memory: 500m
    #   limits:
    #     cpu: 200m
    #     memory: 500m

  listeners:
    client:
      protocol: PLAINTEXT

  extraConfig: |
    num.network.threads=5
    num.io.threads=12

    log.retention.hours=1
    num.partitions=24
    auto.create.topics.enable=true

schema-registry:
  replicaCount: 1
  kafka:
    enabled: false
  externalKafka:
    brokers:
      PLAINTEXT://kafka-cluster.kafka:9092

cp-ksql-server:
  kafka:
    bootstrapServers: "PLAINTEXT://kafka-cluster.kafka:9092"

  ksql:
    headless: false

  prometheus:
    jmx:
      enabled: false

kafka-ui:
  yamlApplicationConfigConfigMap:
    name: *kafkaUIConfigMap
    keyName: dynamic_config.yml
