
kafka:
  controller:
    replicaCount: 3
    persistence:
      enabled: false
    # resources:
    #   requests:
    #     cpu: 200m
    #     memory: 500m
    #   limits:
    #     cpu: 200m
    #     memory: 500m

  broker:
    replicaCount: 4
    persistence:
      enabled: false
    # resources:
    #   requests:
    #     cpu: 200m
    #     memory: 500m
    #   limits:
    #     cpu: 200m
    #     memory: 500m

  listeners:
    client:
      protocol: PLAINTEXT

  extraConfig: |
    num.network.threads=5
    num.io.threads=12

    log.retention.hours=1
    num.partitions=24
    auto.create.topics.enable=true


kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: cluster-0
          bootstrapServers: kafka-cluster.kafka:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
