apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  containers:
    - name: {{ .Values.containerName }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      env:
      {{- toYaml .Values.env | nindent 8 }}
